### ISSUE TITLE
IE Zipcodes

### ISSUE THREAD

**Issue by Lobidu** [sarcadass/i18n-zipcodes#1]
Hi,

what rules are the Irish Zipcodes based on? 

The validator does not accept the rather new Eircode (https://www.eircode.ie/what-is-eircode), instead the pattern looks more british.

If you can explain what the first pattern is, I may be able to create a PR to integrate the Eircode.

Thanks

Janis

**Comment by sarcadass** [comment]
@Lobidu with no response on your side, I close this ticket.
