### ISSUE TITLE
Add support for Colombian zip codes

### ISSUE THREAD

**Issue by zachrattner** [sarcadass/i18n-zipcodes#2]
In Colombia, ZIP codes are 6 digit numeric codes with limitations on each group of 2 digits: https://en.m.wikipedia.org/wiki/Postal_codes_in_Colombia

**Comment by sarcadass** [comment]
Do you want to add this yourself with a PR ?
Can you provide some Colombian zip codes examples please?

**Comment by zachrattner** [comment]
`^\d{6}$` should do the trick - https://en.m.wikipedia.org/wiki/Postal_codes_in_Colombia

**Comment by sarcadass** [comment]
**CO** support added in the latest release (`v2.0.0`).
