### ISSUE TITLE
Incorrect regex for GB

### ISSUE THREAD

**Issue by rpaasche** [sarcadass/i18n-zipcodes#22]
The Regex dose not recognize all ZIP codes:

The following is a valid zip codes but did not get recognizes:

CR0 0XZ
Postleitzahl in Croydon, England

**Comment by rpaasche** [comment]
Correct REGEX:
^(([A-Z]{1,2}[0-9][A-Z0-9]?|ASCN|STHL|TDCU|BBND|[BFS]IQQ|PCRN|TKCA) ?[0-9][A-Z]{2}|BFPO ?[0-9]{1,4}|(KY[0-9]|MSR|VG|AI)[ -]?[0-9]{4}|[A-Z]{2} ?[0-9]{2}|GE ?CX|GIR ?0A{2}|SAN ?TA1)$

See: https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom

**Comment by sarcadass** [comment]
Hello @rpaasche,
Can you open a Pull request with the updated Regex ?

**Comment by rpaasche** [comment]
Hallo @sarcadass 
sorry, just saw this bug is invalid, there was an other bug on our site.
