### ISSUE TITLE
Add support for GB post codes

### ISSUE THREAD

**Issue by zachrattner** [sarcadass/i18n-zipcodes#3]
Seems valid GB post codes are being marked as a invalid, e.g., `EC1V 0DX`

Wikipedia provides this post code format: `^[A-Z]{1,2}[0-9][A-Z0-9]? ?[0-9][A-Z]{2}$` 

https://en.wikipedia.org/wiki/Postcodes_in_the_United_Kingdom

Can we change the regex to this?

**Comment by sarcadass** [comment]
I see on the article that there is even a more precise one: `^(([A-Z]{1,2}[0-9][A-Z0-9]?|ASCN|STHL|TDCU|BBND|[BFS]IQQ|PCRN|TKCA) ?[0-9][A-Z]{2}|BFPO ?[0-9]{1,4}|(KY[0-9]|MSR|VG|AI)[ -]?[0-9]{4}|[A-Z]{2} ?[0-9]{2}|GE ?CX|GIR ?0A{2}|SAN ?TA1)$`.

Can you open a PR after updating the existing regexp in `lib/zipRegexLib.js:13` ?

BTW you never answered my comment in this other issue you created https://github.com/sarcadass/i18n-zipcodes/issues/2.

**Comment by zachrattner** [comment]
Your call since it's your project. I haven't tested the more precise one, but the one I suggested in the initial request worked for the few I spot checked it with.

I tried to make a PR but got a permission denied error. Any suggestions?

Will check the other issue now, missed the message originally. My b.

**Comment by sarcadass** [comment]
Can you test the zipcodes that were not validated here: https://regex101.com/r/AHYtSr/3.

If you want to make a PR, you first need to fork the repo: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork.

If you don't plan to do it, tell me and I will update the lib soon.

**Comment by zachrattner** [comment]
I don't plan to do it

**Comment by sarcadass** [comment]
Regex updated in the latest release (`v2.0.0`).
⚠️**GB** key has been replaced by **UK** key.

**Comment by zachrattner** [comment]
@sarcadass If you replaced `gb` with `uk` key, you might want to update https://www.npmjs.com/package/i18n-zipcodes 

The docs still mention "gb". Might cause some frustration if you leave it as is :)

**Comment by sarcadass** [comment]
Done in the last version.

**Comment by jariz** [comment]
@sarcadass What exactly is your reasoning for renaming GB to UK?
On the [ISO-3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) wiki page (which the readme states that the project is based upon), it even says that UK is called GB.
