### ISSUE TITLE
Incorrect RegEx for Israel

### ISSUE THREAD

**Issue by DosOvO** [sarcadass/i18n-zipcodes#31]
Hi,

i justnoticed that the postcode validation reg ex for israel (il) is wrong. 
Israel can also have 7 (new) digit post codes and not only 5 (old). So it would be better to support both.

https://en.wikipedia.org/wiki/Postal_codes_in_Israel

Greetings
DosOvO

**Comment by sarcadass** [comment]
Hi,
Thank you for raising this issue, would you want to open a PR too?
