### ISSUE TITLE
UK is not a valid ISO-3166-1 code

### ISSUE THREAD

**Issue by jariz** [sarcadass/i18n-zipcodes#8]
GB should be used instead.
See also: https://en.wikipedia.org/wiki/ISO_3166-1

However, let's alias UK to GB, for:
1) backwards compatibility reasons 
2) it apparently being reserved by the United Kingdom within ISO-3166-1, and therefore being safe to use.

This will not make the library completely spec compliant, but seeing as it's not right now eitherway, what's the harm?

**Comment by sarcadass** [comment]
Thank for the PR, let stay with that backward compatibility for now.
I will force the use of `GB` in a future major release.

**Comment by sarcadass** [comment]
Your fix is available on the latest release.
